# Generated by Django 2.2.9 on 2020-03-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUbicacion', models.CharField(choices=[('s', 'Salon'), ('e', 'Edificio'), ('eq', 'Equipo')], default='s', max_length=20)),
                ('nombre', models.CharField(max_length=45)),
                ('esContenedor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('2020-1', '2020-1'), ('2020-2', '2020-2'), ('2020-1', '2021-1'), ('2020-2', '2021-2')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('comentario', models.CharField(max_length=250)),
                ('fechaResolucion', models.DateField()),
                ('esSiniestro', models.BooleanField(default=False)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saaacd.Ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
